name: task_sphere
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0+5

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^7.1.1
  equatable: ^2.0.5
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.6
  flutter_screenutil: ^5.8.4
  intl: ^0.18.1
  sliver_tools: ^0.2.10
  flutter_reorderable_list: ^1.3.1
  very_good_infinite_list: ^0.7.0
  url_launcher: ^6.1.11
  vanilla_state: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/space_grotesk/bold.ttf
          weight: 700
        - asset: assets/fonts/space_grotesk/medium.ttf
          weight: 500
        - asset: assets/fonts/space_grotesk/regular.ttf
          weight: 400
    - family: WorkSans
      fonts:
        - asset: assets/fonts/work_sans/medium.ttf
          weight: 500
        - asset: assets/fonts/work_sans/regular.ttf
          weight: 400

